version: '3.8'
services:
  socket:
    depends_on:
      - db
      - redis
    image: quickplaymod/quickplay-socket
    ports:
      - "54678:80"
      - "5859:5859"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    env_file:
      - .env
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - ../redis-volume:/var/lib/redis
  proxy:
    image: quickplaymod/quickplay-asset-proxy
    ports:
      - "32182:80"
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ../db-volume:/var/lib/mysql
    env_file:
      - docker-db.env
  portal:
    image: quickplaymod/quickplay-portal
    depends_on:
      - db
      - redis
      - socket
    ports:
      - "43515:80"
    restart: unless-stopped
    env_file:
      - portal.env
