version: '3.8'
services:
  web:
    depends_on:
      - db
    image: quickplaymod/quickplay-socket
    ports:
      - "54678:80"
    restart: unless-stopped
    volumes:
      - ./glyphs:/usr/src/app/glyphs
    env_file:
      - socket.env
  redis:
    image: redis:6
    restart: unless-stopped
    volumes:
      - ./redis-data:/var/lib/redis
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/mysql
    env_file:
      - docker-db.env
