version: '3.8'
services:
  socket:
    depends_on:
      - db
    image: quickplaymod/quickplay-socket
    ports:
      - "54678:80"
    restart: unless-stopped
    env_file:
      - socket.env
  proxy:
    image: quickplaymod/quickplay-asset-proxy
    ports:
      - "32182:80"
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: redis:6
    restart: unless-stopped
    volumes:
      - ./redis-data:/var/lib/redis
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/mysql
    env_file:
      - docker-db.env
  portal:
    image: quickplaymod/quickplay-portal
    depends_on:
      - db
      - redis
      - socket
    ports:
      - "43515:80"
    restart: unless-stopped
    env_file:
      - portal.env
